#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KotAtGentAPI.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="STUDENT_nan.cao@kahosl.be")]
	public partial class KotAtGentDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKotAtGent_Type(KotAtGent_Type instance);
    partial void UpdateKotAtGent_Type(KotAtGent_Type instance);
    partial void DeleteKotAtGent_Type(KotAtGent_Type instance);
    partial void InsertKotAtGent_Zone(KotAtGent_Zone instance);
    partial void UpdateKotAtGent_Zone(KotAtGent_Zone instance);
    partial void DeleteKotAtGent_Zone(KotAtGent_Zone instance);
    #endregion
		
		public KotAtGentDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["STUDENT_nan_cao_kahosl_beConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KotAtGentDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KotAtGentDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KotAtGentDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KotAtGentDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<KotAtGent_Kot> KotAtGent_Kots
		{
			get
			{
				return this.GetTable<KotAtGent_Kot>();
			}
		}
		
		public System.Data.Linq.Table<KotAtGent_Type> KotAtGent_Types
		{
			get
			{
				return this.GetTable<KotAtGent_Type>();
			}
		}
		
		public System.Data.Linq.Table<KotAtGent_Zone> KotAtGent_Zones
		{
			get
			{
				return this.GetTable<KotAtGent_Zone>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KotAtGent_Kots")]
	public partial class KotAtGent_Kot
	{
		
		private int _ID;
		
		private string _Zone;
		
		private string _Adres;
		
		private string _Eigennaar_naam;
		
		private string _Eigennaar_telefoon;
		
		private string _Eigennaar_email;
		
		private System.Nullable<int> _Kamers;
		
		private System.Nullable<decimal> _Min_prijs;
		
		private System.Nullable<decimal> _Max_prijs;
		
		private string _Type;
		
		private System.Nullable<double> _Lat;
		
		private System.Nullable<double> _Long;
		
		private string _Beschrijving;
		
		public KotAtGent_Kot()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zone", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Zone
		{
			get
			{
				return this._Zone;
			}
			set
			{
				if ((this._Zone != value))
				{
					this._Zone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="VarChar(255)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this._Adres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eigennaar_naam", DbType="VarChar(255)")]
		public string Eigennaar_naam
		{
			get
			{
				return this._Eigennaar_naam;
			}
			set
			{
				if ((this._Eigennaar_naam != value))
				{
					this._Eigennaar_naam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eigennaar_telefoon", DbType="VarChar(255)")]
		public string Eigennaar_telefoon
		{
			get
			{
				return this._Eigennaar_telefoon;
			}
			set
			{
				if ((this._Eigennaar_telefoon != value))
				{
					this._Eigennaar_telefoon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eigennaar_email", DbType="VarChar(255)")]
		public string Eigennaar_email
		{
			get
			{
				return this._Eigennaar_email;
			}
			set
			{
				if ((this._Eigennaar_email != value))
				{
					this._Eigennaar_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kamers", DbType="Int")]
		public System.Nullable<int> Kamers
		{
			get
			{
				return this._Kamers;
			}
			set
			{
				if ((this._Kamers != value))
				{
					this._Kamers = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Min_prijs", DbType="Money")]
		public System.Nullable<decimal> Min_prijs
		{
			get
			{
				return this._Min_prijs;
			}
			set
			{
				if ((this._Min_prijs != value))
				{
					this._Min_prijs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Max_prijs", DbType="Money")]
		public System.Nullable<decimal> Max_prijs
		{
			get
			{
				return this._Max_prijs;
			}
			set
			{
				if ((this._Max_prijs != value))
				{
					this._Max_prijs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(255)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lat", DbType="Float")]
		public System.Nullable<double> Lat
		{
			get
			{
				return this._Lat;
			}
			set
			{
				if ((this._Lat != value))
				{
					this._Lat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Long", DbType="Float")]
		public System.Nullable<double> Long
		{
			get
			{
				return this._Long;
			}
			set
			{
				if ((this._Long != value))
				{
					this._Long = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Beschrijving", DbType="VarChar(MAX)")]
		public string Beschrijving
		{
			get
			{
				return this._Beschrijving;
			}
			set
			{
				if ((this._Beschrijving != value))
				{
					this._Beschrijving = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KotAtGent_Type")]
	public partial class KotAtGent_Type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    #endregion
		
		public KotAtGent_Type()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KotAtGent_Zone")]
	public partial class KotAtGent_Zone : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Zone;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnZoneChanging(string value);
    partial void OnZoneChanged();
    #endregion
		
		public KotAtGent_Zone()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zone", DbType="VarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Zone
		{
			get
			{
				return this._Zone;
			}
			set
			{
				if ((this._Zone != value))
				{
					this.OnZoneChanging(value);
					this.SendPropertyChanging();
					this._Zone = value;
					this.SendPropertyChanged("Zone");
					this.OnZoneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
